
template header
pageNum
form
id
question
type
options
weighting
salience

package com.redhat.wizard
import com.redhat.wizard.*
import java.util.LinkedList;

template "wizard"

rule "wizard_@{row.rowNumber}"
salience @{row.rowNumber}
when
    l:LinkedList()
then
    Control ctl=new Control(
    Integer.parseInt("@{pageNum}"),
    "@{form}", 
    Integer.parseInt("@{id}"), 
    "@{question}", 
    "@{type}" 
    ,"@{options}"
    ,Integer.parseInt("@{weighting}")
    );
    l.add(ctl);
end

end template